---

- name: Including distro-specific variables
  include_vars: "vars_{{ ansible_distribution }}.yml"
  
- name: "Setting things up for {{ ansible_distribution }}"
  include: "setup_{{ ansible_distribution }}.yml"
  when: ansible_distribution in [ 'Ubuntu', 'Gentoo' ]

- name: "Ensuring services are started and enabled"
  action: service name={{ item }} state=started enabled=yes
  with_items: "{{ mage_services }}"

- name: "Ensuring /etc/sysctl.d/99-containers.conf is set"
  template: 
    src: containers.j2
    dest: /etc/sysctl.d/99-containers.conf
    mode: 0644

- name: sysctl
  shell: "sysctl -p"